version: '3.4'

services:
  fantasydb:
    image: mongo

  fantasyteamdb:
    image: redis:alpine

  leaguedb:
    image: postgres

  betdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  fantasyteam.api:
    image: ${DOCKER_REGISTRY-}fantasyteamapi
    build:
      context: .
      dockerfile: src/Services/FantasyTeam/FantasyTeam.API/Dockerfile

  fantasy.api:
    image: ${DOCKER_REGISTRY-}fantasyapi
    build:
      context: .
      dockerfile: src/Services/Fantasy/Fantasy.API/Dockerfile


  league.api:
    image: ${DOCKER_REGISTRY-}leagueapi
    build:
      context: .
      dockerfile: src/Services/League/League.API/Dockerfile

  league.grpc:
    image: ${DOCKER_REGISTRY-}leaguegrpc
    build:
      context: .
      dockerfile: src/Services/League/League.GRPC/Dockerfile

  bet.api:
    image: ${DOCKER_REGISTRY-}betapi
    build:
      context: .
      dockerfile: src/Services/Bet/Bet.API/Dockerfile

volumes:
  mongo_data: 
  portainer_data:
  postgres_data:
  pgadmin_data:

